/**
 * The Worker environment as the application sees it.
 *
 * `Env` is generated by `wrangler types` from `wrangler.jsonc`, so it covers
 * every resource binding and those are guaranteed present at runtime. It cannot
 * know about `wrangler secret put` values, which this type adds.
 */
export type AppEnv = Env & {
  /** Required by Better Auth. Absence breaks sign-in, not an optional feature. */
  BETTER_AUTH_SECRET: string
  /**
   * Required AES key (exactly 32 bytes, hex or base64) for stored credentials:
   * custom SMTP passwords, per-form Turnstile secrets, and webhook signing
   * secrets.
   */
  FORMZERO_ENCRYPTION_KEY: string
  /**
   * Required instance-wide HMAC secret for keyed hashes of request/privacy
   * metadata. Today: client IP for rate-limit keys and (when a form opts in
   * via ipMode) source_ip_hash storage. Not used for auth credentials.
   */
  FORMZERO_HASH_SECRET: string
  /** Public origin used for file links in notification emails. */
  FORMZERO_PUBLIC_URL?: string
  /** Account-wide Turnstile secret, used when a form has no own credential. */
  TURNSTILE_SECRET?: string
}
