/**
 * The Worker environment as the application sees it.
 *
 * `Env` is generated by `wrangler types` from `wrangler.jsonc`, so it covers
 * every resource binding and those are guaranteed present at runtime. It cannot
 * know about `wrangler secret put` values, which this type adds.
 */
export type AppEnv = Env & {
  /** Required by Better Auth. Absence breaks sign-in, not an optional feature. */
  BETTER_AUTH_SECRET: string
  /**
   * Encrypts stored credentials: custom SMTP passwords, per-form Turnstile
   * secrets, and webhook signing secrets. Not needed for the Cloudflare email
   * transport.
   */
  FORMZERO_ENCRYPTION_KEY?: string
  /** Public origin used for file links in notification emails. */
  FORMZERO_PUBLIC_URL?: string
  /** Account-wide Turnstile secret, used when a form has no own credential. */
  TURNSTILE_SECRET?: string
  /** HMAC secret for hashed IP storage and IP-based rate limiting. */
  IP_HASH_SECRET?: string
}
